### ISSUE TITLE
Ошибка при обработке сообщений от другого сервиса в очереди rabbitmq

### ISSUE THREAD

**Issue by budazhapoverdem** [egal/egal-framework-php-package#109]
- Egal Version: fix_service_not_responding
- PHP Version: 7.4

Описание:

При отправке сообщения (методом call) из сервиса с использованием класса Egal\Core\Communication\Request выпадает ошибка

Log:
```sh
[2021-08-11 07:40:53] local.ERROR: Call to a member function getData() on null {"exception":"[object] (Error(code: 0): Call to a member function getData() on null at /app/vendor/egal/framework/core/Communication/Request.php:244)
[stacktrace]
#0 /app/vendor/egal/framework/core/Communication/Request.php(192): Egal\\Core\\Communication\\Request->authorizeService()
#1 /app/vendor/breaker/notification/src/Notifications/ServiceNotification.php(59): Egal\\Core\\Communication\\Request->call()
```

При отключении сервисной авторизации запрос успешно отсылается в другой сервис.

Но, в сервисе - получателе при обработке получаемого сообщения возникает ошибка
```sh
[2021-08-11 08:13:43] local.ERROR: NOT_FOUND - no queue '8d4be3c0-5eb3-4173-b50e-5cda1a72269a' in vhost '/' {"exception":"[object] (PhpAmqpLib\\Exception\\AMQPProtocolChannelException(code: 404): NOT_FOUND - no queue '8d4be3c0-5eb3-4173-b50e-5cda1a72269a' in vhost '/' at /app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:216)
[stacktrace]
#0 [internal function]: PhpAmqpLib\\Channel\\AMQPChannel->channel_close(Object(PhpAmqpLib\\Wire\\AMQPReader))
#1 /app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(217): call_user_func(Array, Object(PhpAmqpLib\\Wire\\AMQPReader))
#2 /app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(374): PhpAmqpLib\\Channel\\AbstractChannel->dispatch('20,40', '\\x01\\x94HNOT_FOUND - ...', NULL)
#3 /app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(677): PhpAmqpLib\\Channel\\AbstractChannel->wait(Array, false, 0)
#4 /app/vendor/egal/framework/core/Bus/RabbitMQBus.php(73): PhpAmqpLib\\Channel\\AMQPChannel->queue_declare('8d4be3c0-5eb3-4...', true)
#5 /app/vendor/egal/framework/core/Jobs/ActionJob.php(91): Egal\\Core\\Bus\\RabbitMQBus->publishMessage(Object(Egal\\Core\\Messages\\StartProcessingMessage))
#6 /app/vendor/egal/framework/core/Jobs/ActionJob.php(55): Egal\\Core\\Jobs\\ActionJob->publishMessageStartProcessing()
#7 /app/vendor/illuminate/queue/Jobs/Job.php(98): Egal\\Core\\Jobs\\ActionJob->handle(Object(Egal\\Core\\Jobs\\RabbitMQJob), Array)
#8 /app/vendor/illuminate/queue/Worker.php(428): Illuminate\\Queue\\Jobs\\Job->fire()
#9 /app/vendor/illuminate/queue/Worker.php(378): Illuminate\\Queue\\Worker->process('rabbitmq', Object(Egal\\Core\\Jobs\\RabbitMQJob), Object(Illuminate\\Queue\\WorkerOptions))
#10 /app/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Consumer.php(123): Illuminate\\Queue\\Worker->runJob(Object(Egal\\Core\\Jobs\\RabbitMQJob), 'rabbitmq', Object(Illuminate\\Queue\\WorkerOptions))
#11 [internal function]: VladimirYuldashev\\LaravelQueueRabbitMQ\\Consumer->VladimirYuldashev\\LaravelQueueRabbitMQ\\{closure}(Object(PhpAmqpLib\\Message\\AMQPMessage))
#12 /app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(1044): call_user_func(Object(Closure), Object(PhpAmqpLib\\Message\\AMQPMessage))
#13 [internal function]: PhpAmqpLib\\Channel\\AMQPChannel->basic_deliver(Object(PhpAmqpLib\\Wire\\AMQPReader), Object(PhpAmqpLib\\Message\\AMQPMessage))
#14 /app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(220): call_user_func(Array, Object(PhpAmqpLib\\Wire\\AMQPReader), Object(PhpAmqpLib\\Message\\AMQPMessage))
#15 /app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(374): PhpAmqpLib\\Channel\\AbstractChannel->dispatch('60,60', '\\vschedule_33\\x00\\x00\\x00...', Object(PhpAmqpLib\\Message\\AMQPMessage))
#16 /app/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Consumer.php(145): PhpAmqpLib\\Channel\\AbstractChannel->wait(NULL, true, NULL)
#17 /app/vendor/illuminate/queue/Console/WorkCommand.php(117): VladimirYuldashev\\LaravelQueueRabbitMQ\\Consumer->daemon('rabbitmq', 'schedule.198639...', Object(Illuminate\\Queue\\WorkerOptions))
#18 /app/vendor/illuminate/queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Console\\WorkCommand->runWorker('rabbitmq', 'schedule.198639...')
#19 /app/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Console/ConsumeCommand.php(48): Illuminate\\Queue\\Console\\WorkCommand->handle()
#20 /app/vendor/illuminate/container/BoundMethod.php(36): VladimirYuldashev\\LaravelQueueRabbitMQ\\Console\\ConsumeCommand->handle()
#21 /app/vendor/illuminate/container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#22 /app/vendor/illuminate/container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#23 /app/vendor/illuminate/container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Egal\\Core\\Application), Array, Object(Closure))
#24 /app/vendor/illuminate/container/Container.php(651): Illuminate\\Container\\BoundMethod::call(Object(Egal\\Core\\Application), Array, Array, NULL)
#25 /app/vendor/illuminate/console/Command.php(136): Illuminate\\Container\\Container->call(Array)
#26 /app/vendor/symfony/console/Command/Command.php(299): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#27 /app/vendor/illuminate/console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#28 /app/vendor/symfony/console/Application.php(978): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#29 /app/vendor/symfony/console/Application.php(295): Symfony\\Component\\Console\\Application->doRunCommand(Object(VladimirYuldashev\\LaravelQueueRabbitMQ\\Console\\ConsumeCommand), Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#30 /app/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#31 /app/vendor/illuminate/console/Application.php(92): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#32 /app/vendor/illuminate/console/Application.php(184): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#33 /app/vendor/laravel/lumen-framework/src/Console/Kernel.php(168): Illuminate\\Console\\Application->call('rabbitmq:consum...', Array, NULL)
#34 /app/vendor/illuminate/support/Facades/Facade.php(261): Laravel\\Lumen\\Console\\Kernel->call('rabbitmq:consum...', Array)
#35 /app/vendor/egal/framework/core/Bus/RabbitMQBus.php(196): Illuminate\\Support\\Facades\\Facade::__callStatic('call', Array)
#36 /app/vendor/egal/framework/core/Commands/EgalListenerRunCommand.php(35): Egal\\Core\\Bus\\RabbitMQBus->listenQueue()
#37 /app/vendor/illuminate/container/BoundMethod.php(36): Egal\\Core\\Commands\\EgalListenerRunCommand->handle()
#38 /app/vendor/illuminate/container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#39 /app/vendor/illuminate/container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#40 /app/vendor/illuminate/container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Egal\\Core\\Application), Array, Object(Closure))
#41 /app/vendor/illuminate/container/Container.php(651): Illuminate\\Container\\BoundMethod::call(Object(Egal\\Core\\Application), Array, Array, NULL)
#42 /app/vendor/illuminate/console/Command.php(136): Illuminate\\Container\\Container->call(Array)
#43 /app/vendor/egal/framework/core/Traits/PcntlSignal.php(26): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#44 /app/vendor/symfony/console/Command/Command.php(299): Egal\\Core\\Commands\\EgalListenerRunCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#45 /app/vendor/illuminate/console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#46 /app/vendor/symfony/console/Application.php(978): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#47 /app/vendor/symfony/console/Application.php(295): Symfony\\Component\\Console\\Application->doRunCommand(Object(Egal\\Core\\Commands\\EgalListenerRunCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#48 /app/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#49 /app/vendor/illuminate/console/Application.php(92): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#50 /app/vendor/laravel/lumen-framework/src/Console/Kernel.php(116): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#51 /app/artisan(35): Laravel\\Lumen\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#52 {main}
```

**Comment by l-max** [comment]
Трудноотловимая ошибка.

```php

public function waitReplyMessages(): void
    {
        $this->isConnectionOpenedOrFail();

        $this->response = new Response();
        $this->response->setActionMessage($this);

        $startedAt = Carbon::now('UTC');
        $mustDieAt = (clone $startedAt)->addSeconds(config('app.wait_reply_message_ttl'));

        try {
            while (Carbon::now('UTC') < $mustDieAt) {
                $this->collectRabbitMessageIntoResponse();

                if ($this->response->getActionResultMessage()) {
                    break;
                }

                if ($this->response->getActionErrorMessage()) {
                    break;
                }

                usleep(100);
            }
        } catch (Exception $exception) {
            $this->closeConnection();

            throw $exception;
        }

        $this->setResponseStatusCode();
    }
```

В чем оказался баг:

В docker-compose файле значение переменной  `WAIT_REPLY_MESSAGE_TTL` указывалось с запятой на конце `5,`.

Изза запятой не правильно отрабатывало приведение типов в методе Carbon::addSeconds(int $value = 1).
Строка `'5,'` приводилась внутри метода к `1`.

Соответственно мы даже не заходили в `while (Carbon::now('UTC') < $mustDieAt)`.


Исправление вот тут https://github.com/egal/egal-framework-php-package/commit/5dabd86d7e50dd9557fe80f49bc4ee6ab4ccac39

**Comment by rollsover** [comment]
Завел задачу, чтобы реализовать в основной кодовой базе https://github.com/egal/egal-framework-php-package/issues/113
